# Generated by Django 6.0.2 on 2026-02-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=225)),
                ('logo', models.ImageField(upload_to='media/schools/logos')),
                ('slug', models.SlugField(unique=True)),
                ('contact_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_contact_info', to='base.contactinfo')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_location', to='base.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
