# Generated by Django 6.0.2 on 2026-02-27 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: +233 XX XXX XXXX or 0XX XXX XXXX', regex='^(?:\\+233|0)([235789])[0-9]{8}$')], verbose_name='Primary Phone')),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: +233 XX XXX XXXX or 0XX XXX XXXX', regex='^(?:\\+233|0)([235789])[0-9]{8}$')], verbose_name='Secondary / WhatsApp Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: +233 XX XXX XXXX or 0XX XXX XXXX', regex='^(?:\\+233|0)([235789])[0-9]{8}$')], verbose_name='Emergency Contact Phone')),
                ('whatsapp', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in Ghana format: +233 XX XXX XXXX or 0XX XXX XXXX', regex='^(?:\\+233|0)([235789])[0-9]{8}$')])),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook Profile')),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('other', 'Other')], default='whatsapp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information Records',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="e.g. 'Main Campus', 'East Legon Branch', 'Student Hostel'", max_length=200)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_address', models.CharField(blank=True, help_text='e.g. P.O. Box AN 1234, Accra', max_length=100)),
                ('region', models.CharField(blank=True, choices=[('AH', 'Ahafo'), ('AS', 'Ashanti'), ('BO', 'Bono'), ('BE', 'Bono East'), ('CE', 'Central'), ('EA', 'Eastern'), ('GA', 'Greater Accra'), ('NE', 'North East'), ('NO', 'Northern'), ('OT', 'Oti'), ('SV', 'Savannah'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('VO', 'Volta'), ('WE', 'Western'), ('WN', 'Western North')], max_length=2, verbose_name='Region')),
                ('district', models.CharField(blank=True, max_length=100)),
                ('town_city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the main/primary location?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['region', 'town_city', 'name'],
            },
        ),
    ]
